### ISSUE TITLE
Cannot set imagePullPolicy to "Always"

### ISSUE THREAD

**Issue by safandi-personal** [ElinaValieva/micronaut-quickstarts#16]
I have included this plugin to my Quarkus project and after running command:
gradlew quarkusBuild
It generetes a kubernetes directory under build directory with 4 files:
kubernetes.json
kubernetes.yml
openshift.json
openshift.yml

Now in the openshift.yml file the imagePullPolicy is by default set to "ifNotPresent" i have tried many configs and settings to change it to "Always" but in the end i have to manually edit the file before running:
gradlew openshiftDeploy

Can you please help me on how to set the value of imagepullpolicy to "always"

**Comment by ElinaValieva** [comment]
Hello @safandi!

I think it is possible to set in the main config variable `quarkus.kubernetes.image-pull-policy=Always`.

Reference: https://quarkus.io/guides/deploying-to-kubernetes

**Comment by safandi-personal** [comment]
Nope that does not work for "openshift.yml"

**Comment by ElinaValieva** [comment]
Could you share quarkus version and details how you set property
